WIP

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -67,20 +67,8 @@ jobs:
             - '/go/pkg/mod'
       - run: yarn setup:contracts
       - run: go run ./core local db preparetest
-      - run: |
-          set -o pipefail
-          set +e
-          go test -v -p 4 -parallel 4 ./... > ./output.txt
-          EXITCODE=$?
-          cat ./output.txt | grep "\-\-\- FAIL"
-          echo "Exit code: $EXITCODE"
-          if [[ $EXITCODE == 1 ]]; then
-              echo "Encountered test failures."
-              exit 1
-          else
-              echo "All tests passed!"
-              exit 0
-          fi
+      - run: set -o pipefail
+      - run: go test -v -p 4 -parallel 4 ./... | tee ./output.txt | grep "\-\-\- FAIL" && echo "All passed!" # only show failures
       - store_artifacts:
           path: ./output.txt
 
@@ -526,172 +514,10 @@ workflows:
   version: 2
   test:
     jobs:
-      - check_if_rebase_needed:
-          filters:
-            tags:
-              ignore:
-                - /^v.*/
-                - /^explorer-v.*/
-            branches:
-              ignore:
-                - develop
-                - /^release\/.*/
-                - master
-                - /^hotfix\/.*/
-      - core-go-test-race:
-          filters:
-            tags:
-              only: /^v.*/
       - core-go-test:
           filters:
             tags:
               only: /^v.*/
-      - solidity:
-          filters:
-            tags:
-              only: /^v.*/
-      - geth-postgres:
-          filters:
-            tags:
-              only: /^v.*/
-      - geth-postgres-ts:
-          filters:
-            tags:
-              only: /^v.*/
-      - parity-postgres:
-          filters:
-            tags:
-              only: /^v.*/
-      - parity-postgres-ts:
-          filters:
-            tags:
-              only: /^v.*/
-      - styleguide:
-          filters:
-            tags:
-              only:
-                - /^v.*/
-                - /^explorer-v.*/
-      - json-api-client:
-          filters:
-            tags:
-              only:
-                - /^v.*/
-                - /^explorer-v.*/
-      - operator-ui:
-          filters:
-            tags:
-              only: /^v.*/
-      - rust:
-          filters:
-            tags:
-              only: /^v.*/
-      - explorer:
-          filters: # all branches, and /^explorer-v../ tags for build-publish...
-            tags:
-              only: /^explorer-v.*/
-      - feeds:
-          filters:
-            tags:
-              only:
-                - /^v.*/
-                - /^explorer-v.*/
-      - lint:
-          filters:
-            tags:
-              only:
-                - /^v.*/
-                - /^explorer-v.*/
-      - prepublish_npm:
-          filters:
-            tags:
-              only:
-                - /^v.*/
-                - /^explorer-v.*/
-      - build-publish-explorer:
-          requires:
-            - styleguide
-            - json-api-client
-            - explorer
-          filters:
-            tags:
-              only: /^explorer-v.*/
-      - build-chainlink-sgx:
-          filters:
-            tags:
-              only: /^v.*/
-      - build-publish-chainlink:
-          requires:
-            - core-go-test
-            - geth-postgres
-            - parity-postgres
-            - styleguide
-            - json-api-client
-            - operator-ui
-            - rust
-          filters:
-            tags:
-              only: /^v.*/
-      - build-publish-integration:
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              only:
-                - develop
-      - build-publish-ts-integration:
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              only:
-                - develop
-      - build-publish-cypress-job-server:
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              only:
-                - develop
-      - build-publish-echo-server:
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              only:
-                - develop
-      - build-publish-external-adapter:
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              only:
-                - develop
-      - build-publish-ingester:
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              only:
-                - develop
-      - reportcoverage:
-          requires:
-            - core-go-test
-            - solidity
-            - operator-ui
-            - rust
-            - explorer
-          filters:
-            tags:
-              ignore:
-                - /^v.*/
-                - /^explorer-v.*/
-            branches:
-              ignore:
-                - develop
-                - /^release\/.*/
-                - master
-                - /^hotfix\/.*/
 commands:
   setup-aws-ecr:
     description: "Install aws cli and log docker in ECR"
